### PR TITLE
Merge OWG entrance rando changes

### PR DESCRIPTION
**Pull request by cheuer**
Changes to add OWG logic done by qadan, I just cleaned up the merge conflicts.

Upstream PRs have been made already, refer:
https://github.com/Bonta0/ALttPEntranceRandomizer/pull/23
https://github.com/KevinCathcart/ALttPEntranceRandomizer/pull/17

### CODE REVIEW

**Review by aerinon — APPROVED** [review]

**Review by aerinon — CHANGES_REQUESTED** [review]
Unfortunately, the approval was premature.

Two items that needs to be addressed:

- convert the invalid_dungeon_bunny_revival regions to the new DR regions - right now, you would be required to Dungeon Bunny Revive places you really can't. DR is much more granular and probably should include the SW Pots as well.
- rewrite the find_inaccessible_regions functions to ignore these new glitched connections when OWG is not on. Right now, it would create dungeon layouts requiring the glitches and then fail to generate the seed when checking if the world is still beatable using all the rules

**Comment by cheuer** [comment]
Updated the bunny revival regions. I admit I have no idea what to do about the find_inaccessible_regions function. Could we just not add the new connections if OWG is not on so that it can't use them?

**Comment by compiling** [comment]
Yes, it looks like we need to only add the new connections if OWG is on (in link_entrances / link_inverted_entrances).  The current solution of creating all the connections and setting them to invalid in set_rules is fine for the entrance randomiser, but doesn't work here.

Theoretically, Skull Woods Pot Circle is ok because you get superbunny state.  But banning that is fine.

**Comment by aerinon** [comment]
Believe this all got into DoorDev branch now.

**Pull request closed without merging**
